language: elixir
elixir:
  - '1.10'
otp_release: '23.0'

script:
  - mix format --check-formatted
  - mix dialyzer
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - priv/plts

# jobs:
#   include:
#     - elixir: '1.9'
#       otp_release: '20.0'

deploy:
  provider: script
  script: mix hex.publish --yes
  skip_cleanup: true
  on:
    tags: true
    branch: master
